### ISSUE TITLE
Add japanese language

### ISSUE THREAD

**Issue by JonatasMA** [JonatasMA/work-time-calculator#18]
Add japanese traduction in source code

**Comment by yoshitaka7** [comment]
Hello. I would love to contribute to fixing this issue.
I've only had a quick look at the code, but am I correct in my understanding that the Japanese translation is added to src/assets/js/lang.js?

**Comment by JonatasMA** [comment]
> Hello. I would love to contribute to fixing this issue. I've only had a quick look at the code, but am I correct in my understanding that the Japanese translation is added to src/assets/js/lang.js?

Hello, yes, this is it, thx u :)

**Comment by yoshitaka7** [comment]
Hi. I've created a PR, take a look when you have time!
https://github.com/JonatasMA/work-time-calculator/pull/21

**Comment by JonatasMA** [comment]
thx ;)
